# Generated by Django 5.1.7 on 2025-03-06 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumnos", "0002_alter_alumno_alumno_fecha_nacimiento"),
        ("cursos", "0001_initial"),
        ("terapeutas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sesion",
            fields=[
                ("id_sesion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_sesion", models.DateTimeField(blank=True, null=True)),
                ("asistencia", models.BooleanField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "id_alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alumnos.alumno"
                    ),
                ),
                (
                    "id_curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cursos.curso"
                    ),
                ),
                (
                    "id_terapeuta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="terapeutas.terapeuta",
                    ),
                ),
            ],
            options={
                "db_table": "sesiones",
            },
        ),
    ]
