# Generated by Django 5.1.7 on 2025-03-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('cursos', '0001_initial'),
        ('terapeutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_sesion', models.DateTimeField(blank=True, db_column='fecha_sesion', null=True)),
                ('asistencia', models.BooleanField(blank=True, db_column='asistencia', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('id_terapeuta', models.ForeignKey(db_column='id_terapeuta', on_delete=django.db.models.deletion.CASCADE, to='terapeutas.terapeuta')),
            ],
            options={
                'db_table': 'sesiones',
            },
        ),
    ]
