# Generated by Django 5.1.7 on 2025-03-06 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0002_alter_alumno_alumno_fecha_nacimiento"),
        ("cursos", "0002_alter_curso_id_colegio_alter_curso_nombre_curso"),
        ("sesiones", "0001_initial"),
        ("terapeutas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sesion",
            name="asistencia",
            field=models.BooleanField(blank=True, db_column="asistencia", null=True),
        ),
        migrations.AlterField(
            model_name="sesion",
            name="fecha_sesion",
            field=models.DateTimeField(blank=True, db_column="fecha_sesion", null=True),
        ),
        migrations.AlterField(
            model_name="sesion",
            name="id_alumno",
            field=models.ForeignKey(
                db_column="id_alumno",
                on_delete=django.db.models.deletion.CASCADE,
                to="alumnos.alumno",
            ),
        ),
        migrations.AlterField(
            model_name="sesion",
            name="id_curso",
            field=models.ForeignKey(
                db_column="id_curso",
                on_delete=django.db.models.deletion.CASCADE,
                to="cursos.curso",
            ),
        ),
        migrations.AlterField(
            model_name="sesion",
            name="id_terapeuta",
            field=models.ForeignKey(
                db_column="id_terapeuta",
                on_delete=django.db.models.deletion.CASCADE,
                to="terapeutas.terapeuta",
            ),
        ),
        migrations.AlterField(
            model_name="sesion",
            name="observaciones",
            field=models.TextField(blank=True, db_column="observaciones", null=True),
        ),
    ]
