# Generated by Django 5.1.6 on 2025-03-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumnos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoPadresTutoresLegales",
            fields=[
                ("id_tutor", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mama_nombre",
                    models.CharField(max_length=50, verbose_name="Nombre de la Madre"),
                ),
                (
                    "mama_apellido",
                    models.CharField(
                        max_length=50, verbose_name="Apellido de la Madre"
                    ),
                ),
                (
                    "mama_cedula",
                    models.CharField(max_length=20, verbose_name="Cédula de la Madre"),
                ),
                (
                    "mama_telefono",
                    models.CharField(
                        max_length=20, verbose_name="Teléfono de la Madre"
                    ),
                ),
                (
                    "mama_email",
                    models.EmailField(max_length=50, verbose_name="Email de la Madre"),
                ),
                (
                    "mama_empresa",
                    models.CharField(
                        max_length=100, verbose_name="Empresa de la Madre"
                    ),
                ),
                (
                    "papa_nombre",
                    models.CharField(max_length=50, verbose_name="Nombre del Padre"),
                ),
                (
                    "papa_apellido",
                    models.CharField(max_length=50, verbose_name="Apellido del Padre"),
                ),
                (
                    "papa_cedula",
                    models.CharField(max_length=20, verbose_name="Cédula del Padre"),
                ),
                (
                    "papa_telefono",
                    models.CharField(max_length=20, verbose_name="Teléfono del Padre"),
                ),
                (
                    "papa_email",
                    models.EmailField(max_length=50, verbose_name="Email del Padre"),
                ),
                (
                    "papa_empresa",
                    models.CharField(max_length=100, verbose_name="Empresa del Padre"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=100, verbose_name="Dirección"),
                ),
                (
                    "id_alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="alumnos.alumno",
                        verbose_name="Alumno",
                    ),
                ),
            ],
            options={
                "db_table": "info_padres_tutores_legales",
            },
        ),
    ]
