# Generated by Django 5.1.7 on 2025-03-06 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0002_alter_alumno_alumno_fecha_nacimiento"),
        (
            "info_padres_tutores_legales",
            "0002_alter_infopadrestutoreslegales_direccion",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="id_alumno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="alumnos.alumno",
                verbose_name="Alumno",
            ),
        ),
    ]
