# Generated by Django 5.1.7 on 2025-03-06 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0002_alter_alumno_alumno_fecha_nacimiento"),
        (
            "info_padres_tutores_legales",
            "0003_alter_infopadrestutoreslegales_id_alumno",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="direccion",
            field=models.CharField(
                db_column="direccion",
                max_length=100,
                null=True,
                verbose_name="Dirección",
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="id_alumno",
            field=models.ForeignKey(
                db_column="id_alumno",
                on_delete=django.db.models.deletion.CASCADE,
                to="alumnos.alumno",
                verbose_name="Alumno",
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="id_tutor",
            field=models.AutoField(
                db_column="id_tutor", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="mama_apellido",
            field=models.CharField(
                db_column="mama_apellido",
                max_length=50,
                verbose_name="Apellido de la Madre",
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="mama_cedula",
            field=models.CharField(
                db_column="mama_cedula",
                max_length=20,
                verbose_name="Cédula de la Madre",
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="mama_email",
            field=models.EmailField(
                db_column="mama_email", max_length=50, verbose_name="Email de la Madre"
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="mama_empresa",
            field=models.CharField(
                db_column="mama_empresa",
                max_length=100,
                verbose_name="Empresa de la Madre",
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="mama_nombre",
            field=models.CharField(
                db_column="mama_nombre",
                max_length=50,
                verbose_name="Nombre de la Madre",
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="mama_telefono",
            field=models.CharField(
                db_column="mama_telefono",
                max_length=20,
                verbose_name="Teléfono de la Madre",
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="papa_apellido",
            field=models.CharField(
                db_column="papa_apellido",
                max_length=50,
                verbose_name="Apellido del Padre",
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="papa_cedula",
            field=models.CharField(
                db_column="papa_cedula", max_length=20, verbose_name="Cédula del Padre"
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="papa_email",
            field=models.EmailField(
                db_column="papa_email", max_length=50, verbose_name="Email del Padre"
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="papa_empresa",
            field=models.CharField(
                db_column="papa_empresa",
                max_length=100,
                verbose_name="Empresa del Padre",
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="papa_nombre",
            field=models.CharField(
                db_column="papa_nombre", max_length=50, verbose_name="Nombre del Padre"
            ),
        ),
        migrations.AlterField(
            model_name="infopadrestutoreslegales",
            name="papa_telefono",
            field=models.CharField(
                db_column="papa_telefono",
                max_length=20,
                verbose_name="Teléfono del Padre",
            ),
        ),
    ]
