# Generated by Django 5.1.7 on 2025-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(db_column='id_alumno', primary_key=True, serialize=False)),
                ('alumno_nombre', models.CharField(db_column='alumno_nombre', max_length=50, verbose_name='Nombre del Alumno')),
                ('alumno_apellidos', models.CharField(db_column='alumno_apellidos', max_length=50, verbose_name='Apellidos del Alumno')),
                ('alumno_fecha_nacimiento', models.DateField(blank=True, db_column='alumno_fecha_nacimiento', null=True, verbose_name='Fecha de Nacimiento')),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
    ]
