# Generated by Django 5.1.6 on 2025-03-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="alumno_fecha_nacimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Nacimiento"
            ),
        ),
    ]
