# Generated by Django 5.1.7 on 2025-03-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_alumno_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='alumno_apellidos',
            field=models.CharField(db_column='alumno_apellidos', max_length=50, verbose_name='Apellidos del Alumno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='alumno_fecha_nacimiento',
            field=models.DateField(blank=True, db_column='alumno_fecha_nacimiento', null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='alumno_nombre',
            field=models.CharField(db_column='alumno_nombre', max_length=50, verbose_name='Nombre del Alumno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_alumno',
            field=models.AutoField(db_column='id_alumno', primary_key=True, serialize=False),
        ),
    ]
