# Generated by Django 5.1.7 on 2025-03-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colegios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(db_column='id_curso', primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(blank=True, db_column='nombre_curso', max_length=100, null=True, verbose_name='Nombre del Curso')),
                ('id_colegio', models.ForeignKey(blank=True, db_column='id_colegio', null=True, on_delete=django.db.models.deletion.CASCADE, to='colegios.colegio', verbose_name='Colegio')),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
    ]
