# Generated by Django 5.1.7 on 2025-03-06 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colegios", "0001_initial"),
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="id_colegio",
            field=models.ForeignKey(
                blank=True,
                db_column="id_colegio",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="colegios.colegio",
                verbose_name="Colegio",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="nombre_curso",
            field=models.CharField(
                blank=True,
                db_column="nombre_curso",
                max_length=100,
                null=True,
                verbose_name="Nombre del Curso",
            ),
        ),
    ]
