# Generated by Django 5.1.7 on 2025-03-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_id_colegio_alter_curso_nombre_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id_curso',
            field=models.AutoField(db_column='id_curso', primary_key=True, serialize=False),
        ),
    ]
