# Generated by Django 5.1.7 on 2025-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id_colegio', models.AutoField(db_column='id_colegio', primary_key=True, serialize=False)),
                ('nombre_colegio', models.CharField(db_column='nombre_colegio', max_length=100, verbose_name='Nombre del Colegio')),
            ],
            options={
                'db_table': 'colegios',
            },
        ),
    ]
