# Generated by Django 5.1.7 on 2025-03-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='id_colegio',
            field=models.AutoField(db_column='id_colegio', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='nombre_colegio',
            field=models.CharField(db_column='nombre_colegio', max_length=100, verbose_name='Nombre del Colegio'),
        ),
    ]
