# Generated by Django 5.1.6 on 2025-03-03 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                ("id_alumno", models.AutoField(primary_key=True, serialize=False)),
                (
                    "alumno_nombre",
                    models.CharField(max_length=50, verbose_name="Nombre del Alumno"),
                ),
                (
                    "alumno_apellidos",
                    models.CharField(
                        max_length=50, verbose_name="Apellidos del Alumno"
                    ),
                ),
                (
                    "alumno_fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de Nacimiento"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Terapeuta",
            fields=[
                ("id_terapeuta", models.AutoField(primary_key=True, serialize=False)),
                (
                    "terapeuta_nombre",
                    models.CharField(
                        max_length=50, verbose_name="Nombre del Terapeuta"
                    ),
                ),
                (
                    "terapeuta_apellidos",
                    models.CharField(
                        max_length=50, verbose_name="Apellidos del Terapeuta"
                    ),
                ),
                (
                    "terapeuta_cedula",
                    models.CharField(
                        max_length=20, verbose_name="Cédula del Terapeuta"
                    ),
                ),
                (
                    "terapeuta_telefono",
                    models.CharField(
                        max_length=20, verbose_name="Teléfono del Terapeuta"
                    ),
                ),
                (
                    "terapeuta_email",
                    models.EmailField(
                        max_length=50, verbose_name="Email del Terapeuta"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Colegio",
            fields=[
                ("id_colegio", models.AutoField(primary_key=True, serialize=False)),
                (
                    "colegio",
                    models.CharField(max_length=100, verbose_name="Nombre del Colegio"),
                ),
                (
                    "id_alumno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_rest_midi.alumno",
                        verbose_name="Alumno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                ("id_curso", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre_curso",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nombre del Curso",
                    ),
                ),
                (
                    "id_colegio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_rest_midi.colegio",
                        verbose_name="Colegio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfoPadresTutoresLegales",
            fields=[
                ("id_tutor", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mama_nombre",
                    models.CharField(max_length=50, verbose_name="Nombre de la Madre"),
                ),
                (
                    "mama_apellido",
                    models.CharField(
                        max_length=50, verbose_name="Apellido de la Madre"
                    ),
                ),
                (
                    "mama_cedula",
                    models.CharField(max_length=20, verbose_name="Cédula de la Madre"),
                ),
                (
                    "mama_telefono",
                    models.CharField(
                        max_length=20, verbose_name="Teléfono de la Madre"
                    ),
                ),
                (
                    "mama_email",
                    models.EmailField(max_length=50, verbose_name="Email de la Madre"),
                ),
                (
                    "mama_empresa",
                    models.CharField(
                        max_length=100, verbose_name="Empresa de la Madre"
                    ),
                ),
                (
                    "papa_nombre",
                    models.CharField(max_length=50, verbose_name="Nombre del Padre"),
                ),
                (
                    "papa_apellido",
                    models.CharField(max_length=50, verbose_name="Apellido del Padre"),
                ),
                (
                    "papa_cedula",
                    models.CharField(max_length=20, verbose_name="Cédula del Padre"),
                ),
                (
                    "papa_telefono",
                    models.CharField(max_length=20, verbose_name="Teléfono del Padre"),
                ),
                (
                    "papa_email",
                    models.EmailField(max_length=50, verbose_name="Email del Padre"),
                ),
                (
                    "papa_empresa",
                    models.CharField(max_length=100, verbose_name="Empresa del Padre"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=100, verbose_name="Dirección"),
                ),
                (
                    "id_alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_rest_midi.alumno",
                        verbose_name="Alumno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sesion",
            fields=[
                ("id_sesion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_sesion", models.DateTimeField(verbose_name="Fecha de Sesión")),
                (
                    "id_alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_rest_midi.alumno",
                        verbose_name="Alumno",
                    ),
                ),
                (
                    "id_curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_rest_midi.curso",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "id_terapeuta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_rest_midi.terapeuta",
                        verbose_name="Terapeuta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id_inscripcion",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID de Inscripción",
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Inscripción"
                    ),
                ),
                (
                    "fecha_baja",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Baja"
                    ),
                ),
                (
                    "id_alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_rest_midi.alumno",
                        verbose_name="Alumno",
                    ),
                ),
                (
                    "id_colegio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_rest_midi.colegio",
                        verbose_name="Colegio",
                    ),
                ),
                (
                    "id_curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_rest_midi.curso",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
                "unique_together": {("id_alumno", "id_curso")},
            },
        ),
    ]
