# Generated by Django 5.1.6 on 2025-03-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Terapeuta",
            fields=[
                ("id_terapeuta", models.AutoField(primary_key=True, serialize=False)),
                (
                    "terapeuta_nombre",
                    models.CharField(
                        max_length=50, verbose_name="Nombre del Terapeuta"
                    ),
                ),
                (
                    "terapeuta_apellidos",
                    models.CharField(
                        max_length=50, verbose_name="Apellidos del Terapeuta"
                    ),
                ),
                (
                    "terapeuta_cedula",
                    models.CharField(
                        max_length=20, verbose_name="Cédula del Terapeuta"
                    ),
                ),
                (
                    "terapeuta_telefono",
                    models.CharField(
                        max_length=20, verbose_name="Teléfono del Terapeuta"
                    ),
                ),
                (
                    "terapeuta_email",
                    models.EmailField(
                        max_length=50, verbose_name="Email del Terapeuta"
                    ),
                ),
            ],
            options={
                "db_table": "terapeutas",
            },
        ),
    ]
