# Generated by Django 5.1.7 on 2025-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id_terapeuta', models.AutoField(db_column='id_terapeuta', primary_key=True, serialize=False)),
                ('terapeuta_nombre', models.CharField(db_column='terapeuta_nombre', max_length=50, verbose_name='Nombre del Terapeuta')),
                ('terapeuta_apellidos', models.CharField(db_column='terapeuta_apellidos', max_length=50, verbose_name='Apellidos del Terapeuta')),
                ('terapeuta_cedula', models.CharField(db_column='terapeuta_cedula', max_length=20, verbose_name='Cédula del Terapeuta')),
                ('terapeuta_telefono', models.CharField(db_column='terapeuta_telefono', max_length=20, verbose_name='Teléfono del Terapeuta')),
                ('terapeuta_email', models.EmailField(db_column='terapeuta_email', max_length=50, verbose_name='Email del Terapeuta')),
            ],
            options={
                'db_table': 'terapeutas',
            },
        ),
    ]
