# Generated by Django 5.1.7 on 2025-03-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terapeutas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terapeuta",
            name="id_terapeuta",
            field=models.AutoField(
                db_column="id_terapeuta", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="terapeuta",
            name="terapeuta_apellidos",
            field=models.CharField(
                db_column="terapeuta_apellidos",
                max_length=50,
                verbose_name="Apellidos del Terapeuta",
            ),
        ),
        migrations.AlterField(
            model_name="terapeuta",
            name="terapeuta_cedula",
            field=models.CharField(
                db_column="terapeuta_cedula",
                max_length=20,
                verbose_name="Cédula del Terapeuta",
            ),
        ),
        migrations.AlterField(
            model_name="terapeuta",
            name="terapeuta_email",
            field=models.EmailField(
                db_column="terapeuta_email",
                max_length=50,
                verbose_name="Email del Terapeuta",
            ),
        ),
        migrations.AlterField(
            model_name="terapeuta",
            name="terapeuta_nombre",
            field=models.CharField(
                db_column="terapeuta_nombre",
                max_length=50,
                verbose_name="Nombre del Terapeuta",
            ),
        ),
        migrations.AlterField(
            model_name="terapeuta",
            name="terapeuta_telefono",
            field=models.CharField(
                db_column="terapeuta_telefono",
                max_length=20,
                verbose_name="Teléfono del Terapeuta",
            ),
        ),
    ]
